
TEMPORAL_ACTIVITY_PLAN_TASK_QUEUE: ActivityPlanLocalTaskQueue
TEMPORAL_FEEDBACK_TASK_QUEUE: FeedbackActivityLocalTaskQueue

server:
  port: 8086
temporal:
  activity-plan:
    task-queue-name: ${TEMPORAL_ACTIVITY_PLAN_TASK_QUEUE}
  feedback:
    task-queue-name: ${TEMPORAL_FEEDBACK_TASK_QUEUE}